version: '3.5'
services:
  app:
    build: images/nginx
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ../../src:/var/www/html:delegated
      - sockdata:/sock
    networks:
      - magento-network

  phpfpm:
    image: markoshust/magento-php:5.6-fpm-3
    links:
      - db
    volumes: *appvolumes
    networks:
      - magento-network

  db:
    image: mysql:5.7
    env_file: 
      - ./docker.env
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db_data:/var/lib/mysql
    tty: true
    networks:
      - magento-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - magento-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: 
      - ./docker.env
    ports:
     - 127.0.0.1:8080:80
    networks:
      - magento-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento-network

volumes:
    db_data: {}

networks:
  magento-network:
    driver: bridge